console.log("Hi i am in console.com to see the things that is in the console.com");
var first_name="Adhip ";
var last_name="choudhury";
console.log(first_name);
console.log(last_name);
var full_name= first_name.concat(last_name);
console.log(full_name);
var len= full_name.length;
console.log(len);
var senten1= "I am Adhip. I like to do code";
console.log(senten1);
var senten2= senten1.replace("I","you");
console.log(senten2);
var senten3= senten1.replaceAll("I","you");
console.log(senten3);
var name="ADhIpChOuDHUry";
var lower_case=name.toLowerCase();
var upper_case=name.toUpperCase();
console.log(lower_case);
console.log(upper_case);
var sqrd=Math.sqrt(16);
console.log(sqrd);
var max_num=Math.max(900, 1000);
console.log(max_num);
var min_num=Math.min(1000, 100);
console.log(min_num);
var power=Math.pow(4,90);
console.log(power)
var add=Math.add(90,90);
